//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Express_e_Filing.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class boj5_detail
    {
        public long id { get; set; }
        public Nullable<long> itemNo { get; set; }
        public string userId { get; set; }
        public Nullable<long> shareNumber { get; set; }
        public string shareType { get; set; }
        public Nullable<double> paidAmount { get; set; }
        public Nullable<double> asPaidAmount { get; set; }
        public string shareDocId { get; set; }
        public Nullable<System.DateTime> shareDocDate { get; set; }
        public Nullable<System.DateTime> shareRegExist { get; set; }
        public Nullable<System.DateTime> shareRegOmit { get; set; }
        public long boj5_person_id { get; set; }
    
        public virtual boj5_person boj5_person { get; set; }
    }
}
