//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Express_e_Filing.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class boj5_header
    {
        public long id { get; set; }
        public string userId { get; set; }
        public string accSource { get; set; }
        public string meetingType { get; set; }
        public string meetingNo { get; set; }
        public Nullable<System.DateTime> sourceDate { get; set; }
        public Nullable<double> totalCapital { get; set; }
        public Nullable<long> totalShare { get; set; }
        public Nullable<double> parValue { get; set; }
        public Nullable<long> thaiShareholder { get; set; }
        public Nullable<long> totalThaiShare { get; set; }
        public Nullable<long> foreignShareholder { get; set; }
        public Nullable<long> totalForeignShare { get; set; }
        public string headerStatus { get; set; }
        public Nullable<System.DateTime> yearEnd { get; set; }
    }
}
