//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Express_e_Filing.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class glacc_match
    {
        public long id { get; set; }
        public string accnum { get; set; }
        public string depcod { get; set; }
        public string taxodesc { get; set; }
        public string taxodesc2 { get; set; }
    }
}
