//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Express_e_Filing.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class options
    {
        public long id { get; set; }
        public string key { get; set; }
        public Nullable<double> value_num { get; set; }
        public string value_str { get; set; }
        public Nullable<System.DateTime> value_datetime { get; set; }
    }
}
